# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20170504_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='total_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
