# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20170504_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default=123, max_length=30),
        ),
    ]
